name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # These are the defaults, plus ready_for_review
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
      - name: Ruff format
        run: |
          python checks/format_.py

  license:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
      - name: License check
        run: |
          python checks/licenses.py
  
  requirements:
    name: Requirements check
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
          pip install -r requirements.txt
      - name: Requirements check
        run: |
          python checks/requirements.py

  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
      - name: Ruff lint
        run: |
          python checks/lint_.py
          
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          python checks/pytest_.py
          
  coverage:
    name: Run coverage checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pytest and Coverage check (3.11)
        run: |
          python checks/coverage_.py
  
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checks-superstaq
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Build docs
        run: |
          python checks/build_docs.py

